version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./dev/client/Dockerfile-client-production
    entrypoint: ['sh', './env.sh']
    command: ['npx', 'serve', '-p', '8080', '--single', './_build']
    ports:
      - ${CLIENT_PORT:-4000}:8080
    environment:
      - SERVER_URL='http://localhost:3000'
      - WEBSOCKET_SERVER_URL='http://localhost:3001'

  server:
    build:
      context: ./dev/server
      dockerfile: ./Dockerfile-server
    depends_on:
      - db
    entrypoint:
      [
        'node_modules/.bin/wait-for-it',
        'db:5432',
        '--',
        'sh',
        'scripts/setupDevServer.sh',
      ]
    command:
      [
        'node_modules/.bin/nodemon',
        'startServer.js',
        '--watch',
        'startServer.js',
        '--watch',
        'app.js',
        '--watch',
        'api',
        '--watch',
        'config',
        '--watch',
        'controllers',
        '--watch',
        'models',
        '--watch',
        'services',
        '--watch',
        'scripts',
        '--watch',
        '--ext',
        'js,graphql',
      ]
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-dev}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - PUBSWEET_SECRET=${PUBSWEET_SECRET:-thesecret}
      - SERVER_PORT=${SERVER_PORT:-3000}
      - CLIENT_URL=${CLIENT_URL:-http://0.0.0.0:4000}
    volumes:
      - ./dev/server/api:/home/node/app/api
      - ./dev/server/config:/home/node/app/config
      - ./dev/server/controllers:/home/node/app/controllers
      - ./dev/server/models:/home/node/app/models
      - ./dev/server/scripts:/home/node/app/scripts
      - ./dev/server/services:/home/node/app/services

  db:
    image: postgres:15
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-dev}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    # volumes:
    #   - ./scripts/init-pgboss.sql:/docker-entrypoint-initdb.d/init-pgboss.sql
